# Site settings
title: Camille Diez
email: diezcami@gmail.com
description: >
  Software Development, General Programming and Unix
baseurl: "/blog" 
url: "http://diezcami.github.io"
twitter_username: 
github_username:  diezcami

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]