# Site settings
title: Camille Diez
email: diezcami@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Development, General Programming and Unix
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://diezcami.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  diezcami

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]